### ISSUE TITLE
RealmConfigurationBase vs. RealmConfiguration

### ISSUE THREAD

**Issue by adolgov** [sushihangover/RealmThread#15]
Are there plans to allow RealmThread to work with Realm Mobile Platform (i.e. construct RealmThread from RealmConfigurationBase rather than RealmConfiguration in order to allow for a possible SyncConfiguration to be used)?

**Comment by sushihangover** [comment]
@adolgov  I originally posted that as a bug with Realm as it was a breaking change, they called it a feature :-/ The fact that you can not use the configuration returned from an Realm instance to create another Realm instance without casting it to me is a "bug" (or bad design/code smell).

I need to issue a PR from my private repo for that as I have "fixed" it for my clients are using it with 0.81.0+ w/ sync or not... I'll try to get that release on nuget.org by end day if all goes well.

Thanks for bump.

**Comment by sushihangover** [comment]
Release: https://github.com/sushihangover/RealmThread/releases/tag/0.4.0

@adolgov This is a push of the `Realm.Database` v.1.1.0 updates. 

FYI: I need to migrate and add tests for `Realm` (RMP) and its notifications, so if you find any problems, please submit an issue (Thanks!)

**Comment by adolgov** [comment]
What's the correct usage for RealmThread with a SyncConfiguration? The constructor only seems to take a RealmConfiguration.

**Comment by sushihangover** [comment]
@adolgov `Realm.Thread` is dependent only on `Realm.Database` so users not using RMP do not have to install `Realm` (which holds a dependency to `Realm.Database`), thus `RealmThread` is looking for a `RealmConfigurationBase`.

Pass a `RealmConfigurationBase` from:
* A `Realm` instance that was *already* created with a `SyncConfiguration` (`Realm.Config` property)
* A non-synced `RealmConfiguration`-based instance (`Realm.Config` property)
* Pass a `RealmConfiguration` directly to create a stand-alone non-synced Realm instance

i.e.:

```
	const string realmDBName = "SyncingWith.Realm";
	RealmThread realmThread;
	var uri = new Uri("http://caliroll:9080");
	await User.LoginAsync(Credentials.UsernamePassword("sushi@not.exist", "sushi", false), uri);
	var user = User.Current;
	if (user != null)
	{
		var url = new Uri("realm://caliroll/2MillionRecordSyncTest.Realm");
		var syncConf = new SyncConfiguration(user, uri, realmDBName);

		masterRealmInstance = Realms.Realm.GetInstance(syncConf);
		realmThread = new RealmThread(masterRealmInstance.Config);
	}
	else
	{
		masterRealmInstance = Realms.Realm.GetInstance(realmDBName);
		realmThread = new RealmThread(new RealmConfiguration(realmDBName));
	}

	if (masterRealmInstance.All<ARealmObject>().Count() == 0)
	{
		realmThread.Invoke((Realms.Realm r) =>
		{
			CreateAndUpdateByGroup(1024 * 1024 * 2, 1024 * 4);
		});
	};

```

**Comment by adolgov** [comment]
This is what I was expecting; however, when I try to construct a `new RealmThread(...)`, I only have a constructor for `RealmConfiguration` rather than `RealmConfigurationBase`. I'm using the latest (0.4.0) from nuget.

This is in a PCL project. I'm not sure how the RealmThread project is structured, but I did notice that the `RealmThread.Shared` project has the constructor defined with `RealmConfigurationBase`; however, the `RealmThread.Portable` project still requires `RealmConfiguration`.

**Comment by sushihangover** [comment]
@adolgov You ca absolutely correct, that would be a bug, I missed the PCL updates 

Issue #17

**Comment by sushihangover** [comment]
@adolgov I just pushed an updated Nuget from AppVeyor (SushiHangover.RealmThread.0.4.1.nupkg) it should just work now (but I have not tested it directly: #19)
